#ifndef CONSTANTS_H
#define CONSTANTS_H


const float PROGRAM_VERSION = 1.005;

const int BASE_WELL_WIDTH   = 8;

const int MAX_WELL_WIDTH    = 16;
const int MAX_WELL_HEIGHT   = 1.75*MAX_WELL_WIDTH;

const float GUI_UNIT_W =10;
const float GUI_UNIT_H =GUI_UNIT_W*1.75;

const int SIMPLE_BUTTON_ALPHA=140;
const int GLASS_BUTTON_ALPHA=200;

const int MAX_PROFILENAME_LENGTH=15;

enum GAME_RANDOMNESS
{
    RANDOMNESS_LOW=0,
    RANDOMNESS_MODERATE,
    RANDOMNESS_HIGH,
    RANDOMNESS_HIGHEST,
    NUM_RANDOMNESS_LEVELS
};

enum GAME_PRESSURE
{
    PRESSURE_NONE=0,
    PRESSURE_MODERATE,
    PRESSURE_HIGH,
    PRESSURE_HIGHEST,
    NUM_PRESSURE_TYPES
};

enum BALL_COLORS
    {
        COLOR_WHITE=0,
        COLOR_BLACK,
        COLOR_RED,
        COLOR_GREEN,
        COLOR_BLUE,
        COLOR_PURPLE,
        COLOR_YELLOW,
        COLOR_ORANGE,
        COLOR_BOMB,
        COLOR_SHIFTER,
        COLOR_LEVELER,
        COLOR_PAINTER,
        COLOR_CHROME,
        NUM_BALLCOLORS,
        NUM_SPECIALBALLS=5,
        COLOR_BLOCK=COLOR_CHROME+1,
        COLOR_REFLECTOR,
        NUM_OBSTACLES=2
   };

enum SCORE_TYPES
{
    SCORE_BOMB=0,
    SCORE_EXPLODED,
    SCORE_DROPPED,
    SCORE_MATCHED
};

enum AXIAL_NEIGHBORS
{
    NEIGHBOR_LEFT=0,
    NEIGHBOR_RIGHT,
    NEIGHBOR_TOP,
    NEIGHBOR_BOTTOM,
    NUM_AXIAL_NEIGHBORS,
    NEIGHBOR_NEXT,
    NEIGHBOR_PREVIOUS
};

enum MOVEMENT_DIRECTION
{
    VERTICAL=0,
    HORIZONTAL,
    MANHATTAN,
    FREE_MOVEMENT
};

enum TEXTCOLORS
{
    COLOR_BACKGROUND=0,
    COLOR_ORIGINAL_BACKGROUND,
    COLOR_WELL_BACKGROUND,
    COLOR_TIMESTOP_BACKGROUND,

    COLOR_PAGE_TITLE,

    COLOR_INGAME_MESSAGE,
    COLOR_INGAME_BGSTAT,
    COLOR_INGAME_BORDERSTAT,
    COLOR_INGAME_BGBEST,
    COLOR_INGAME_BORDERBEST,

    COLOR_NOBG1,
    COLOR_NOBG2,
    COLOR_NOBG3,
    COLOR_NOBG4,

    COLOR_TEXT1,
    COLOR_TEXT2,
    COLOR_TEXT3,
    COLOR_TEXT4,

    COLOR_WARNING,
    COLOR_MAXVARIATION,

    NUM_TEXTCOLORS
};

enum SUMMONS
{
    UNL_NONE=0,
    UNL_BOMB,
    UNL_COLORSHIFTER,
    UNL_TIMESTOP,
    UNL_PAINTER,
    UNL_LEVELER,
    UNL_CHROME,
    NUM_SUMMONS
};

#ifndef EXTRA_GAME_MODES
//#define EXTRA_GAME_MODES
#endif


enum UNLOCKABLES
{
    UNL_TRUERANDOM,
    UNL_CHAOS,
    UNL_SKIN_DARK2,
    UNL_SKIN_LIGHT2,
    UNL_SKIN_PATTERN2,
    UNL_SKIN_GEOMETRIC2,
    UNL_MATCH4,
    UNL_MATCH5,
    UNL_MATCH6,
    UNL_DIM10,
    UNL_DIM12,
    UNL_DIM14,
    UNL_DIM16,
#ifdef EXTRA_GAME_MODES
    UNL_MODE_TIME,
    UNL_MODE_SHOT,
    UNL_MODE_SCORE,
    UNL_EDITOR,
#endif
    NUM_UNLOCKABLES,
};

enum DIMENSIONS
{
    DIM_8=0,
    DIM_10,
    DIM_12,
    DIM_14,
    DIM_16,
    NUM_DIMENSIONS
};

enum GAME_MODES//tied with above unlockables, and levelstat passed bit offsets
{
    GM_NORMAL=0,
    GM_TIMELIMIT,
    GM_SHOTLIMIT,
    GM_SCORELIMIT,
    NUM_GAME_MODES
};

enum SOUND_EFFECTS
{
    SFX_TAP1=0,
    SFX_TAP2,
    SFX_PAGESCROLL,
    SFX_MENUPOP,
    SFX_SWAP,
    SFX_BUBBLE,
    SFX_LAUNCH,
    SFX_LAUNCH2,
    SFX_COLLISION,
    SFX_COLLISION2,
    SFX_LAND,
    SFX_LAND2,
    SFX_LANDFAIL,
    SFX_DROP,
    SFX_DROP2,
    SFX_DROP3,
    SFX_DROP4,
    SFX_POP,
    SFX_POP2,
    SFX_POP3,
    SFX_POP4,
    SFX_POP5,
    SFX_POP6,
    SFX_POP7,
    SFX_EXPLODE,
    SFX_EXPLODE2,
    SFX_EXPLODE3,
    SFX_EXPLODE4,
    SFX_COLORSHIFTER,
    SFX_PAINTER,
    SFX_BOMB,
    SFX_LEVELER,
    SFX_CHROME,
    SFX_TIMESTOP,
    NUM_SOUND_EFFECTS
};

#endif

